fix: font's format fixed to truetype
Jarmos-san/jarmos.dev pull request #351
Opened 2024-02-17 05:52 UTC by Sagar-Kap

This PR will fix the Poppins font's format in the [assets](https://github.com/Jarmos-san/jarmos.dev/blob/main/web/public/assets/Poppins-Regular.ttf) directory. Fixing this format fixes the font in the viewport (#350) , the solution is based on this [Stack Overflow](https://stackoverflow.com/a/76724886) thread.

![image](https://github.com/Jarmos-san/jarmos.dev/assets/69609200/75709bf8-60d7-42b2-8521-a37f9808269e)

2024-02-18 19:35 UTC, Jarmos-san requested changes
Thanks for providing the fix, I had totally missed it before! Btw if you can, could you also change the font files from `.ttf` to a more optimised and [recommended `.woff2` file format](https://fonts.google.com/knowledge/glossary/web_font)?

2024-02-19 09:31 UTC, Sagar-Kap commented
> Thanks for providing the fix, I had totally missed it before! Btw if you can, could you also change the font files from `.ttf` to a more optimised and [recommended `.woff2` file format](https://fonts.google.com/knowledge/glossary/web_font)?

[Fontsource](https://www.npmjs.com/package/@fontsource/poppins) library is being used now for fonts so the concern about optimization will be taken care of by the npm library.

2024-02-19 09:32 UTC, Sagar-Kap reviewed
The fontsource library will be used now so this is redundant.

2024-02-19 09:45 UTC, Jarmos-san approved these changes

2024-02-19 09:45 UTC, merged